### PR TITLE
Jkmarx/fix dashboard search bugs

### LINKED ISSUE #2967: Dashboard text search doesn't interact with paging
* Specific code commit: f6b5665211815395d5ee7246a3e3574b1692eb72
* Version of the web browser and OS: FF on Max
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Production Test

### Steps to reproduce
Please list all the actions and the input data used:

1. On the new Dashboard, do a text search

### Observed behavior

The found set hasn't actually changed: We still have the multiple paging buttons below, even though there was just one match. This is confusing, and really won't work if there is more than one page of search results.

screen shot 2018-08-29 at 10 41 30 am

### Expected behavior
* Probably the paging should correspond to the results found with the text search.

### PR DESCRIPTION
**Pull request by jkmarx**
Resolves #2967 
Also fixes this new bug with highlight
screen shot 2019-02-06 at 11 10 43 am

Fixed:
screen shot 2019-02-06 at 12 46 07 pm

### CODE REVIEW

File: refinery/ui/source/js/dashboard/controllers/data-sets-card-ctrl.js [hunk 1]
```diff
@@ -229,13 +232,20 @@
     function searchDataSets (query) {
       // reset perm filter until we can search & check perms
       vm.groupFilter = { selectedName: 'All' };
+      vm.params = { limit: vm.itemsPerPage, offset: vm.pageStartOffset };
       if (query && query.length > 1) {
         vm.loadingDataSets = true;
         var apiRequest = new DataSetSearchApi(query);
-        apiRequest(200).then(function (response) {
+        apiRequest(100).then(function (response) {
```
Comment (scottx611x) [inline refinery/ui/source/js/dashboard/controllers/data-sets-card-ctrl.js]: Not understanding the need for a `100` instead of a `200` here

Comment (jkmarx) [reply refinery/ui/source/js/dashboard/controllers/data-sets-card-ctrl.js]: Oops, good catch. It's the number of ds returned.
