### PR TITLE
 Fix visual bug with tool tip.

### LINKED ISSUE #1884: Same page link on the Collaboration page
Commit: 

While on the Collaboration page click on the "?" next to `Groups` in the first column header.
There is a link in the popover text to the collaboration page (which we are currently on). 
Seems a bit unnecessary.
screen shot 2017-07-07 at 4 41 18 pm

### PR DESCRIPTION
**Pull request by jkmarx**
Ref #1886 
Resolves #1884 
When on the data set share -- ? tooltip, clicking the link 'data_set_preview' doesn't visually do anything since the user is already on the data set preview page.
Update html by adding a component and template for the new logic.

to-collab-page
to-dashboard

### CODE REVIEW

File: refinery/ui/source/js/commons/ctrls/sharing-help-popover-details-ctrl.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+    vm.isCollaborationPage = false;
+
+   /*
+   * ---------------------------------------------------------
+   * LifeCycle Hooks
+   * ---------------------------------------------------------
+   */
+    vm.$onInit = function () {
+      // check if the user is on the collaboration page
+      vm.isCollaborationPage = $location.absUrl().indexOf('collaboration') > -1;
```
Comment (mccalluc) [inline refinery/ui/source/js/commons/ctrls/sharing-help-popover-details-ctrl.js]: Would it be worth while to be more precise here? `/collaboration/` should begin the path?

Comment (jkmarx) [reply refinery/ui/source/js/commons/ctrls/sharing-help-popover-details-ctrl.js]: I wouldn't imagine so, since the popover is just use on the home and collaboration page. But, I can add it.

File: refinery/ui/source/js/commons/partials/sharing-help-popover-details.html [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+  with an authenticated user, create a new group or invite the user to an
+  existing group
+  <span ng-if="!$ctrl.isCollaborationPage">
+    <a href='/collaboration'> on the collaboration page. </a> Owners can
+    update data set permissions (including making it public) on the data set
+    preview by clicking the “sharing” button.
+  </span>
+  <span ng-if="$ctrl.isCollaborationPage">
+    on the collaboration page. Owners can update data set permissions
+    (including making it public) on the <a href='/#'> data set preview </a> by
```
Comment (mccalluc) [inline refinery/ui/source/js/commons/partials/sharing-help-popover-details.html]: Could this be more confusing than useful? We can't actually take them to the data set preview, but if we just take them to the dashboard, there isn't going to be a "sharing" button for them to click either.

Comment (jkmarx) [reply refinery/ui/source/js/commons/partials/sharing-help-popover-details.html]: @mccalluc Good point. How about this revised text: 
"Only data set owners can change sharing options. To share
  with an authenticated user, create a new group or invite the user to an
  existing group on the collaboration page. Owners can update data set permissions (including making it public) on the <a href=/#> dashboard </a> by opening a data set preview (click a data set link) and then clicking the “sharing” button."

Comment (mccalluc) [reply refinery/ui/source/js/commons/partials/sharing-help-popover-details.html]: That sounds good.
