### PR TITLE
Jkmarx/hide user files column

### LINKED ISSUE #2350: User/files Empty Columns
* Specific code commit: 09a2aa2e7e739fb286f370258e899dfe27f5d9c5
* Version of the web browser and OS: Mac OSX
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
 Test site

### Steps to reproduce
Please list all the actions and the input data used:

1.  Open the user files page
2. Sort Date or Experimenter

### Observed behavior
column-empty

### Expected behavior
* If columns are empty, should they even be shown?

### LINKED ISSUE #2458: Add columns/facets to cross filebrowser to meet Shivdasani lab needs
Talking with @gmnelson: Currently we have a column for the filename. Instead:
- Have a column for the sample name: This should be filled in, and is more likely to be useful: The filename could have been chosen arbitrarily by the processing center.
- Have a column for the original local path: This is actually what the lab needs, since they will only be using it for metadata.
- Add a filetype facet, and a column, because a facet without a column might be odd?
- and *remove* the current filename column: It is redundant with path.

And:
- Change "Date" to "Date Submitted" (but there seems to be some deeper problem with the rendering of the Date column? #2350)

### PR DESCRIPTION
**Pull request by jkmarx**
-This is a temp solution to not create columns for attributes which do not have any fields. There is another bug which is causing empty columns. Specifically, attributes which have fields but the fields all return 0. Wondering if it's a local issue? Ref #2352
Generally resolves #2350 
Resolves #2458 

- [x] Fix columns which don't have facet counts

### CODE REVIEW

File: refinery/ui/source/js/user-file-browser/services/factory.js [hunk 1]
```diff
@@ -68,8 +68,13 @@
                   '</a>' +
                 '</div>',
             width: 30 }];
+      // temp solution to handle empty columns until backend is updated to
+      // avoid sending attributes with no fields
+      var validateAttributeStr = culledAttributes.join('');
       settings.djangoApp.userFilesColumns.forEach(function (column) {
-        defs.push({ field: column });
+        if (validateAttributeStr.indexOf(column) > -1) {
```
Comment (mccalluc) [inline refinery/ui/source/js/user-file-browser/services/factory.js]: I'd worry about getting false positives from chance concatenations... Could you use the array instead?
```javascript
_.contains(culledAttributes, column)
```
(or a built-in, if the JS version we're targetting supports it.)

Comment (jkmarx) [reply refinery/ui/source/js/user-file-browser/services/factory.js]: @mccalluc I need to make a few other changes also, but yes your suggestion makes sense.

**Comment by jkmarx** [comment]
@mccalluc Sorry, I actually wasn't ready for this pull request to be reviewed. I added & then removed you as a reviewer.
