### PR TITLE
Jkmarx/isa tab upload enhancement

### LINKED ISSUE #2691: Data Set Import -> Associated data files waiting to be uploaded bug
* Specific code commit: 07fa2fc90223e14336c5547c4d8238ec03fd648b
* Version of the web browser and OS: Chrome
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): Test instance

### Steps to reproduce
Please list all the actions and the input data used:

1. Metadata Import or Isatab Import, add file
2. Select add data sets and add any file

### Observed behavior
screen shot 2018-03-23 at 8 14 07 am

### Expected behavior
* When you have data files selected, you should not be able to upload without adding them. 

https://github.com/refinery-platform/refinery-platform/commit/14c9190d8565a8c09cf866d8982690a01116aec5

### PR DESCRIPTION
**Pull request by jkmarx**
Resolves #2691 

Disable while files are in queue or uploads
disable-while-files-in-queue

Disable bottom half which no files are referenced
screen shot 2018-08-13 at 11 10 46 am

### CODE REVIEW

**Comment by jkmarx** [comment]
@mccalluc Both builds have passed but aren't updating here.

File: refinery/ui/source/js/data-set-import/controllers/isa-tab-import.js [hunk 1]
```diff
@@ -28,6 +50,16 @@
     this.closeError = function () {
       this.isErrored = false;
     };
+
+    // helper watcher which updates the upload file status from component
+    $scope.$watchCollection(
+      function () {
+        return fileUploadStatusService.fileUploadStatus;
+      },
```
Comment (mccalluc) [inline refinery/ui/source/js/data-set-import/controllers/isa-tab-import.js]: I'm not seeing why the `Collection` part is necessary here: I can see you've moved the real status down into a property, but could you just add it here, too, and use plain `watch`? Sorry not to get it.

File: refinery/ui/source/js/data-set-import/services/file-upload-status-service.js [hunk 2]
```diff
@@ -13,9 +13,9 @@ function fileUploadStatusService () {
   vm.setFileUploadStatus = function (status) {
     var statusOptions = ['none', 'queuing', 'running'];
     if (statusOptions.indexOf(status) > -1) {
-      vm.fileUploadStatus = status;
+      vm.fileUploadStatus.status = status;
     }
-    return vm.fileUploadStatus;
+    return vm.fileUploadStatus.status;
```
Comment (mccalluc) [inline refinery/ui/source/js/data-set-import/services/file-upload-status-service.js]: This is just the input value? Does anything need the return value?

File: refinery/ui/source/js/data-set-import/controllers/isa-tab-import.js (hunk 1 above)
Comment (mccalluc) [reply refinery/ui/source/js/data-set-import/controllers/isa-tab-import.js]: data-file-edit-modal-ctrl.js for comparison.

File: refinery/ui/source/js/data-set-import/services/file-upload-status-service.js (hunk 2 above)
Comment (jkmarx) [reply refinery/ui/source/js/data-set-import/services/file-upload-status-service.js]: Not necessarily (index of values). Yes.

File: refinery/ui/source/js/data-set-import/controllers/isa-tab-import.js (hunk 1 above)
Comment (jkmarx) [reply refinery/ui/source/js/data-set-import/controllers/isa-tab-import.js]: @mccalluc For this instance, watch would work vs watchCollection since we're not adding any additional properties. watchCollection just tends to be my default for objects. Will adjust.

Comment (jkmarx) [reply refinery/ui/source/js/data-set-import/controllers/isa-tab-import.js]: @mccalluc We've discussed this in a previous pull request. Issues with setting primitives in services. https://github.com/refinery-platform/refinery-platform/pull/2921 

Bottom line it a javascript thing when it comes to primitives versus watching references (obj, arrays). Did you get a chance to look at the references I posted previously in pull request 2921?
