### PR TITLE
Jkmarx/upgrade to ubuntu 16

### LINKED ISSUE #3118: Upgrade to Ubuntu 16.04 LTS
Currently used version 14.04.5 LTS has end of life date April 2019
Ubuntu 16.04.5 LTS has end of life date April 2021
https://wiki.ubuntu.com/Releases

[Travis CI has 16.04 available now](https://blog.travis-ci.com/2018-11-08-xenial-release)

See also: #1813 and #2616 

- https://wiki.ubuntu.com/XenialXerus/ReleaseNotes

### LINKED ISSUE #3387: Missing Dependency - linux-image-extra-3.13.0-170-generic
* Specific code commit:  7507863c3c663152d99863ea5c381109130570f6
* Version of the web browser and OS: Mac Mojave 10.14.1
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
Vagrant VM

### Steps to reproduce
Please list all the actions and the input data used:

1. Spin up a new instance

### Observed behavior
```default: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install linux-image-extra-3.13.0-170-generic' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E: Unable to locate package linux-image-extra-3.13.0-170-generic
==> default: E: Couldn't find any package by regex 'linux-image-extra-3.13.0-170-generic'
==> default: 
==> default: Error: /Stage[main]/Docker::Install/Package[linux-image-extra-3.13.0-170-generic]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install linux-image-extra-3.13.0-170-generic' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E: Unable to locate package linux-image-extra-3.13.0-170-generic
==> default: E: Couldn't find any package by regex 'linux-image-extra-3.13.0-170-generic'
==> default: 
==> default: Warning: /Stage[main]/Docker::Install/Package[docker]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Docker::Config/Docker::System_user[vagrant]/Exec[docker-system-user-vagrant]: Dependency Package[linux-image-extra-3.13.0-170-generic] has failures: true
```

### Expected behavior
* No Error.

**Also noticed on the Ubuntu 16 upgrade branch.**
https://github.com/refinery-platform/refinery-platform/tree/jkmarx/upgrade-to-ubuntu-16
  [UbuntuUpdates - Package "linux-modules-extra-4.4.0-148-generic" (xenial 16.04)](https://www.ubuntuupdates.org/package/core/xenial/main/proposed/linux-modules-extra-4.4.0-148-generic)

### PR DESCRIPTION
**Pull request by jkmarx**
- Upgrade ubuntu Resolves #3118 
    - Switched to xenial box http://releases.ubuntu.com/16.04/
    - Note, Vagrant recommends Bento Boxes https://www.vagrantup.com/docs/boxes.html#official-boxes
- Install puppet (v14 included puppet 3)
     -https://stackoverflow.com/questions/48897383/vagrant-puppet-provision-failure-error-msg-the-puppet-binary-appears-not-to 
- Upgrade solr java library 
    - Issues with v7 on ubuntu 16. v8 is compatible with our version of solr
    - https://lucene.apache.org/solr/5_3_1/SYSTEM_REQUIREMENTS.html
- Update postgresql-10 package
    - https://www.ubuntuupdates.org/package/postgresql/xenial-pgdg/main/base/postgresql-10
- Upgrade paramiko
    - ubuntu compatibility issue
- Update docker.pp to avoid managing kernel due to a dependency default setting Resolves #3387 
    - https://forge.puppet.com/garethr/docker

### CODE REVIEW

File: Vagrantfile [hunk 1]
```diff
@@ -10,8 +10,8 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   # please see the online documentation at vagrantup.com.
 
   # Every Vagrant virtual environment requires a box to build off of.
-  config.vm.box = "ubuntu/trusty64"
-  config.vm.box_version = "20181203.0.1"
+  config.vm.box = "ubuntu/xenial64"
```
Comment (hackdna) [inline Vagrantfile]: You decided not to use bento boxes after all?
https://www.vagrantup.com/docs/boxes.html#official-boxes

File: deployment/bootstrap.sh [hunk 2]
```diff
@@ -14,6 +14,8 @@ set -x
 
 /usr/bin/apt-get -q -y install git htop nmon ruby-dev tree
 
+/usr/bin/apt-get -y install puppet
```
Comment (hackdna) [inline deployment/bootstrap.sh]: `puppet` should be added to the line above (alphabetized)
